Fixed DStress tests nocompile/c/{const_32_B.d,const_32_C.d}. Updated the runtest script to build libtangobos-partial.a if it hasn't already been built. Added in signbit() and va_arg!()() to libtangobos-partial.a so more of the phobos dependent DStress tests pass.

diff --git a/tests/runtest b/tests/runtest
--- a/tests/runtest
+++ b/tests/runtest
@@ -7,6 +7,14 @@ if [ -z "$1" ] ; then
 fi
 TARGETFILE=$1
 
+# check for libtangobos-partial
+if ! [ -f testincludes/libtangobos-partial.a ] ; then
+    echo "Could not find libtangobos-partial.a, attempting to build."
+    cd testincludes
+    make
+    cd ..
+fi
+
 # check for dstress
 if ! [ -d dstress ] ; then
     echo "Testing requires DStress to be checked out into dstress/"
