Try to tweak CircleCI

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -66,10 +66,10 @@ commonSteps: &commonSteps
             -DCMAKE_BUILD_TYPE=Release \
             -DD_COMPILER=$PWD/../host-ldc/bin/ldmd2 \
             $EXTRA_CMAKE_FLAGS
-          # Work around out-of-memory errors - retry twice with -j2 and one last time with -j1
+          # Work around out-of-memory errors - retry twice with parallelization and one last time serially
           targets='all ldc2-unittest all-test-runners'
           for i in {1..3}; do
-            ninja -j2 $targets && break || true
+            ninja -j$PARALLELISM $targets && break || true
           done
           ninja -j1 $targets
           bin/ldc2 -version
@@ -80,7 +80,7 @@ commonSteps: &commonSteps
     - run:
         name: Run LIT testsuite
         when: always
-        command: cd ../build && ctest -V -R lit-tests
+        command: cd ../build/tests && python runlit.py -v -j $PARALLELISM .
     - run:
         name: Run DMD testsuite
         when: always
@@ -90,11 +90,11 @@ commonSteps: &commonSteps
             # Circle's RAM disk FS apparently doesn't allow long paths.
             rm ../project/tests/d2/dmd-testsuite/compilable/issue17167.sh
           fi
-          DMD_TESTSUITE_MAKE_ARGS=-j3 ctest -V -R dmd-testsuite
+          DMD_TESTSUITE_MAKE_ARGS=-j$PARALLELISM ctest -V -R dmd-testsuite
     - run:
         name: Run defaultlib unittests & druntime stand-alone tests
         when: always
-        command: cd ../build && ctest -j3 --output-on-failure -E "dmd-testsuite|ldc2-unittest|lit-tests"
+        command: cd ../build && ctest -j$PARALLELISM --output-on-failure -E "dmd-testsuite|ldc2-unittest|lit-tests"
 
 version: 2
 jobs:
@@ -103,6 +103,7 @@ jobs:
     docker:
       - image: ubuntu:18.04
     environment:
+      - PARALLELISM: 2
       - CI_OS: linux
       - LIBCLANG_COMMON_VERSION: "6.0"
       - HOST_LDC_VERSION: 1.19.0
@@ -112,6 +113,7 @@ jobs:
     docker:
       - image: ubuntu:rolling
     environment:
+      - PARALLELISM: 2
       - CI_OS: linux
       - LIBCLANG_COMMON_VERSION: "9"
       - EXTRA_APT_PACKAGES: gdmd
@@ -122,6 +124,7 @@ jobs:
     macos:
       xcode: "11.3.1"
     environment:
+      - PARALLELISM: 4
       - CI_OS: osx
       - LLVM_VERSION: 9.0.1
       - HOST_LDC_VERSION: 1.19.0
@@ -131,6 +134,7 @@ jobs:
     macos:
       xcode: "11.3.1"
     environment:
+      - PARALLELISM: 4
       - CI_OS: osx
       - LLVM_VERSION: 9.0.1
       - HOST_LDC_VERSION: 1.19.0
